---
- name: Update and Upgrade
  apt:
    upgrade: full
    cache_valid_time: 3600

# https://docs.ansible.com/ansible/latest/user_guide/playbooks_handlers.html#notifying-handlers
# "Handlers are executed in the order they are defined in the handlers section, not in the order listed in the notify statement."
# Therefore, putting the reboot handler last.

- name: Restart
  reboot:
