---
- name: Copy the Public SSH key to the Host
  authorized_key:
    user: "{{ ansible_user }}"
    state: present
    key: "{{ pub_key }}"

- name: Set Privileged User PW
  user:
    name: "{{ ansible_user }}"
    password: "{{ root_pw | password_hash('sha512', root_pw_salt) }}"
