--- 
hypervisors:
  hosts:
    pve:
      # the management interface is manually configured during bare-metal install
      ansible_host: 192.168.0.3
      # # ansible configures the lan interface
      # lan_iface: enp8s0
      # lan_vbridge: vmbr1
  vars:
    # manually entered during bare-metal install. ansible will change to something more secure.
    ansible_password: "easypass"

containers:
  hosts:
    dns:
      ansible_host: 192.168.0.5
    proxy:
      ansible_host: 192.168.0.2
    cookbook:
      ansible_host: 192.168.0.4
    wedding:
      ansible_host: 192.168.0.6
    cransible:
      ansible_host: 192.168.0.7

  vars:
    vcpus: 1
    ram: 1024
    disk_size: 4
    tgt_storage: "local-lvm"
    netconf: '{"net0":"name=eth0,gw={{ netenv.gw }},ip={{ ansible_host }}/{{ netenv.mask }},bridge={{ netenv.vbridge }}"}'
