--- 
hypervisors:
  hosts:
    pve:
      # a temporary management interface is configured during the bare-metal install.
      # ansible will change because the full configuration requires vlans
      ansible_host: 192.168.27.10
    # TEMPORARY HOST FOR TESTING
    pvetmp:
      # a temporary management interface is configured during the bare-metal install.
      # ansible will change because the full configuration requires vlans
      ansible_host: 192.168.0.3
  vars:
    # manually entered during bare-metal install.
    # ansible will change to something more secure.
    ansible_password: "easypass"

containers:
  hosts:
    ddns:
      ansible_host: 192.168.29.5
    proxy:
      ansible_host: 192.168.29.2
    cookbook:
      ansible_host: 192.168.29.4
    love:
      ansible_host: 192.168.29.6
    homepage:
      ansible_host: 192.168.29.7
  vars:
    vcpus: 1
    ram: 1024
    disk_size: 4
    tgt_storage: "local-lvm"
    netconf: '{"net0":"name=eth0,gw={{ dmz_netenv.gw }},ip={{ ansible_host }}/{{ dmz_netenv.mask }},bridge=vmbr0,tag={{ dmz_netenv.vlan }}"}'

jekyllsites:
  hosts:
    cookbook:
    love:
    homepage:
