---
hypervisors:
  hosts:
    pve:
  vars:
    # manually entered during bare-metal install.
    # ansible will change to something more secure.
    ansible_password: "easypass"

containers:
  hosts:
    frigate:
      vcpus: 4
      ram: 4096
      disk_size: 512
      netconf: '{"net0":"name=eth0,ip=dhcp,bridge=vmbr0,tag=28,hwaddr={{ vault_frigate_mac_addr }}"}'
    revproxy:
      netconf: '{"net0":"name=eth0,ip=dhcp,bridge=vmbr0,tag=29,hwaddr={{ vault_revproxy_mac_addr }}"}'
      ddns_app_dir: "/home/{{ usr_name }}/ddns_client"
  vars:
    vcpus: 1
    ram: 1024
    disk_size: 4
    tgt_storage: "local-lvm"
    os: debian
