---
hypervisors:
  hosts:
    pve:
  vars:
    # manually entered during bare-metal install.
    # ansible will change to something more secure.
    ansible_password: "easypass"

containers:
  hosts:
    frigate:
      container_id: 243
      vcpus: 4
      ram: 4096
      disk_size: 512
      netconf: '{"net0":"name=eth0,ip=dhcp,bridge=vmbr0,tag=28,hwaddr={{ vault_frigate_mac_addr }}"}'
      passthrough_devices:
        - "dev0: /dev/dri/renderD128"
        - "dev1: /dev/kfd"
    nginx:
      container_id: 729
      netconf: '{"net0":"name=eth0,ip=dhcp,bridge=vmbr0,tag=29,hwaddr={{ vault_nginx_mac_addr }}"}'
      ddns_app_dir: "/home/{{ usr_name }}/ddns_client"
  vars:
    vcpus: 1
    ram: 1024
    disk_size: 4
    tgt_storage: "local-lvm"
    os: debian
