--- 
hypervisors:
  hosts:
    pve:
      # a temporary management interface is configured during the bare-metal install.
      # ansible will change because the full configuration requires vlans
      ansible_host: 192.168.27.10
  vars:
    # manually entered during bare-metal install.
    # ansible will change to something more secure.
    ansible_password: "easypass"

containers:
  hosts:
    dns:
      ansible_host: 192.168.0.5
    proxy:
      ansible_host: 192.168.0.2
    cookbook:
      ansible_host: 192.168.0.4
    love:
      ansible_host: 192.168.0.6
    homepage:
      ansible_host: 192.168.0.7
  vars:
    vcpus: 1
    ram: 1024
    disk_size: 4
    tgt_storage: "local-lvm"
    netconf: '{"net0":"name=eth0,gw={{ netenv.gw }},ip={{ ansible_host }}/{{ netenv.mask }},bridge={{ netenv.vbridge }}"}'

jekyllsites:
  hosts:
    cookbook:
    love:
    homepage:
