---
hypervisors:
  hosts:
    pve:
      ansible_host: pve.local
      # a temporary management interface is configured during the bare-metal install.
      # ansible will change because the full configuration requires vlans
  vars:
    # manually entered during bare-metal install.
    # ansible will change to something more secure.
    ansible_password: "easypass"

raspberry_pies:
  hosts:
    model4b:
      ansible_host: model4b.local
      ansible_user: marcus
      ddns_app_dir: "/home/{{ usr_name }}/ddns_client"

containers:
  hosts:
    moby:
      vcpus: 4
      ram: 4096
      disk_size: 16
      mac_addr: "{{ vault_moby_mac_addr }}"

  # bitcoin:
  #   ansible_host: 192.168.29.9
  #   disk_size: 750
  #   vcpus: 16
  #   ram: 16384
  #   os: ubuntu
  # turn:
  #   ansible_host: 192.168.29.10
  # microtalk:
  #   ansible_host: 192.168.29.11
  #   os: ubuntu
  vars:
    vcpus: 1
    ram: 1024
    disk_size: 4
    tgt_storage: "local-lvm"
    # netconf: '{"net0":"name=eth0,gw={{ dmz_netenv.gw }},ip={{ ansible_host }}/{{ dmz_netenv.mask }},bridge=vmbr0,tag={{ dmz_netenv.vlan }}"}'
    os: debian

vms:
  hosts:
    workstation:
      ansible_host: 192.168.27.4
      ansible_user: arch

jekyllsites:
  hosts:
    cookbook:
    love:
    homepage:
