--- 
hypervisors:
  hosts:
    pve:
      # the management interface is manually configured during bare-metal install
      dmz_vbridge: vmbr0
      ansible_host: 192.168.0.3
      # ansible configures the lan interface
      lan_iface: enp8s0
      lan_vbridge: vmbr1
  vars:
    # manually entered during bare-metal install. ansible will change to something more secure.
    ansible_password: "easypass"

containers:
  hosts:
    router:
      ansible_host: 192.168.27.1
      secondary_ip: 192.168.0.299.107.120.140
      dns_srvr: "{{ netenv.dmz.dns }}"
      netconf:
        net0: a # "name=eth0,ip={{ ansible_host }}/{{ netenv.lan.mask }},bridge={{ netenv.lan.vbridge }}"
        net1: b #"name=eth1,ip={{ secondary_ip }}/{{ netenv.dmz.mask }},bridge={{ netenv.dmz.vbridge }},gw={{ netenv.dmz.gw }}"
  vars:
    vcpus: 1
    ram: 1024
    disk_size: 4
    tgt_storage: "local-lvm"
