services:
  frigate:
    container_name: frigate
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    network_mode: host
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ~/config:/config
      - ~/media:/media/frigate
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1g
    # because i am running two full resolution streams
    # with one of of them at 30fps
    # error logs suggest a size of "at least 342MB"
    # actual usage is around 437 MiB
    shm_size: 512m
