# object detection hardware and models
detectors:
  ov:
    type: openvino
    device: CPU
model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  path: /openvino-model/ssdlite_mobilenet_v2.xml
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt

# object types and alerts
detect:
  enabled: true
objects:
  track:
    - cat
review:
  alerts:
    labels:
      - cat

# recording
record:
  enabled: true
  retain:
    days: 3
    mode: all
  detections:
    retain:
      days: 9
      mode: all
  alerts:
    retain:
      days: 27
      mode: all

# save audio on the recordings
ffmpeg:
  output_args:
    record: preset-record-generic-audio-copy

# feeds directly from camera
go2rtc:
  streams:
    food:
      - ffmpeg:https://foodcam.local/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=qS7kef9TzrBoQl4h
    counter:
      - ffmpeg:https://countercam.local/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=qS7kef9TzrBoQl4h

# cameras pick up re-streams
cameras:
  food:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/food
          roles:
            - detect
            - record
    motion:
      mask: 0.296,0,0.293,0.034,0.002,0.034,0.002,0.002
    zones:
      Countertop:
        coordinates: 
          0.499,0.184,0.635,0.178,0.637,0.102,0.775,0.108,0.804,0.058,0.87,0.068,0.995,0.233,0.992,0.431,0.907,0.293,0.847,0.366,0.717,0.371,0.694,0.301,0.518,0.29
    review:
      alerts:
        required_zones: Countertop
  counter:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/counter
          roles:
            - detect
            - record
    motion:
      mask: 0.296,0,0.692,0.002,0.691,0.027,0.297,0.025
    zones:
      Whole_Palace:
        coordinates: 0.041,0.331,0.039,0.961,0.932,0.957,0.903,0.321
    review:
      alerts:
        required_zones: Whole_Palace
# mqtt
mqtt:
  enabled: false
version: 0.15-1
