services:
  frigate:
    container_name: frigate
    restart: unless-stopped
    # for object detection via Radeon Open CoMpute.
    image: ghcr.io/blakeblackshear/frigate:stable-rocm
    environment:
      # for video encoding/decoding based on INTEL's Video Acceleration API (VA-API) specification
      # The radeonsi driver, part of the Mesa project, is specifically used for OpenGL support on AMD GPUs
      - LIBVA_DRIVER_NAME=radeonsi
      # this part is always tricky
      # https://github.com/ollama/ollama/blob/main/docs/gpu.md#overrides-on-linux
      # https://docs.frigate.video/configuration/object_detectors#docker-settings-for-overriding-the-gpu-chipset
      # https://rocm.docs.amd.com/en/latest/reference/gpu-arch-specs.html
      # https://rocm.docs.amd.com/projects/install-on-linux/en/latest/reference/system-requirements.html
      - HSA_OVERRIDE_GFX_VERSION=10.3.0
    devices:
      - /dev/dri
      - /dev/kfd
    network_mode: host
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ~/config:/config
      - ~/media:/media/frigate
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1g
    # because i am running two high resolution (5MP) streams
    # error logs suggest a size of "at least 342MB"
    # actual usage is around 437 MiB
    shm_size: 512m
