---
- name: Set Git User
  git_config:
    name: user.name
    value: "{{ git_name }}"
    scope: global

- name: Set Git Email
  git_config:
    name: user.email
    value: "{{ git_email }}"
    scope: global
