---
- name: pcie passthrough
  hosts: pve
  handlers:
    - import_tasks: handlers/main.yml
  tasks:
    - name: iommu kernel parameter (via grub)
      lineinfile:
        path: /etc/default/grub
        search_string: "GRUB_CMDLINE_LINUX_DEFAULT="
        line: 'GRUB_CMDLINE_LINUX_DEFAULT="iommu=pt"'
      register: kernel_parms
      notify: Restart

    - shell:
        cmd: update-grub
      when: kernel_parms.changed

    - name: vfio kernel modules
      lineinfile:
        dest: /etc/modules
        line: "{{ item }}"
      with_items:
        - "vfio"
        - "vfio_iommu_type1"
        - "vfio_pci"
      notify: Restart

    - name: modprobe options
      lineinfile:
        dest: /etc/modprobe.d/gpu-passthrough.conf
        create: true
        line: "{{ item }}"
      with_items:
        - blacklist amdgpu
        - options vfio-pci ids=1002:73df
      notify: Restart
