# object detection hardware and models
detectors:
  ov:
    type: openvino
    device: CPU
model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  path: /openvino-model/ssdlite_mobilenet_v2.xml
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt

# object types and alerts
detect:
  enabled: true
objects:
  track:
    - cat
review:
  alerts:
    labels:
      - cat

# recording
record:
  enabled: true
  retain:
    days: 3
    mode: all
  detections:
    retain:
      days: 9
      mode: all
  alerts:
    retain:
      days: 27
      mode: all

# save audio on the recordings and use hardware accelerated encoding/decoding
ffmpeg:
  output_args:
    record: preset-record-generic-audio-copy
  hwaccel_args: preset-vaapi

# feeds directly from camera
go2rtc:
  streams:
    living_room:
      - ffmpeg:https://livingroomcam.local/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password={{ vault_camera_pw }}
    palace:
      - ffmpeg:https://palacecam.local/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password={{ vault_camera_pw }}

# cameras pick up re-streams
cameras:
  living_room:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/living_room
          roles:
            - detect
            - record
    motion:
      mask: 0.296,0,0.293,0.034,0.002,0.034,0.002,0.002
    zones:
      Countertop:
        coordinates: 0.527,0.199,0.655,0.198,0.652,0.132,0.787,0.132,0.811,0.08,0.893,0.092,1,0.234,1,0.448,0.924,0.335,0.859,0.439,0.704,0.44,0.669,0.331,0.551,0.331
      Coffee_Table:
        coordinates: 0.495,0.366,0.501,0.551,0.672,0.516,0.677,0.425,0.661,0.335
    review:
      alerts:
        required_zones:
          - Countertop
          - Coffee_Table
  palace:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/palace
          roles:
            - detect
            - record
    motion:
      mask: 0.296,0,0.692,0.002,0.691,0.027,0.297,0.025
    zones:
      Front_Gate:
        coordinates: 0.041,0.331,0.039,0.961,0.932,0.957,0.903,0.321
    review:
      alerts:
        required_zones: Front_Gate

# notifications
mqtt:
  enabled: false
notifications:
  enabled: true
  email: "{{ usr_email }}"

# software version (auto added/updated by frigate)
version: 0.15-1
