---
# these items will need to change if you're not vincent saelzler
git_email: vincent.saelzler@gmail.com
git_name: Vincent Saelzler
usr_email: vincent.saelzler@gmail.com # for certbot

dmz_netenv:
  mask: 24
  gw: 192.168.29.1
  dns: 192.168.29.1
  vlan: 29

# copied from files/id_rsa.pub
pub_key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCdu/Dolq85/sScWhdmnFNpxYuCQtq6lPCuD/CcXbwy9TC372z7ZF2dvsWx0uHZFnTbbcuwvNmrR/g2yROAmzoppEGvio8fIuv/iQ7V1lmplrBR1TWenr58S0PtHZ6NleGBuI3j6HSskoNwx3hRq9WyCvHdtWZ769tMRSOgG7YJJLyp4w0fX4cSeWwcSOhHhgVojI6/kqMIsEmeX691XDYT3vFLlY8Lsd/Qzr6qe08o1xyzENOjUIT84fO/IKjvxQ6msIkcR/NrgELLz3M8GgMtdLU5w8+yTvM/xOEyaHxodpOloVkMBI4U/O4QXkyvO1GpyQq1YiQ+yg4O1Ul086wonxqj+BF+iktAmH9Vh+SjCiYRaOZn8GwUPkJ1zTz7xogtX7GOcnanYH2DXIIFfb8hVKdGrLdwZknyuHLie2rUctBYvmZ48yR1O6GrIclHj22WnYsji+LZqZ87IwBODTvfLSfIDcWFKb0l1IJzJNKcoErETWQekVnYC9lZeRhMdBs= ansible"

ansible_user: root
api_user: root@pam

# the unprivileged user
usr_name: pleb
full_name: Plebian

# web applications
domains: 
  # - hearty.cooking
  # - saelzler.org
  # - vincentsaelzler.com
  - quercusphellos.online

# the certbot role expects a list of ~certificates~
# each certificate could have one or more domains
# CANNOT USE MULTIPLE DOMAINS ON ONE CERT FOR NOW
# TASK [Create symbolic links for intermediate certificate chains]
# fails
certs:
  # - domains:
  #   - hearty.cooking
  # - domains:
  #   - saelzler.org
  # - domains:
  #   - vincentsaelzler.com
  - domains:
    - quercusphellos.online

# credentials
# if the PWs here are not stored externally, and the ansible vault PW is lost,
# THERE IS NO WAY TO RECOVER!!
root_pw:  "{{ vault_root_pw }}"
pw_salt: "{{ vault_pw_salt }}"
usr_pw:  "{{ vault_usr_pw }}"

porkbun_apikey: "{{ vault_porkbun_apikey }}"
porkbun_secretapikey: "{{ vault_porkbun_secretapikey }}"
