---
# these items will need to change if you're not vincent saelzler
git_email: vincent.saelzler@gmail.com
git_name: Vincent Saelzler
usr_email: vincent.saelzler@gmail.com # for certbot

dmz_netenv:
  mask: 24
  gw: 192.168.29.1
  dns: 192.168.29.1
  vlan: 29

# copied from files/id_rsa.pub
pub_key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCyjAeKiP4H0PQVFEXjhulQLq9aNBAWfODq1PZi4x2sZaAFeaIJUKaS10oXya4/BsbZ/lxmla9E/jUmyP100GR7w46hfm5r9xjEf+Abbow7VpEh544UtVTm43eTFcO+OLck/3GUmTgkOBb0x+1aPtsTvMU5gjMaHu4AE0OBG0TWsiFH1eiAlZcw1/gR4APNBzTCljp5yfrqiicIRO1EB8V2mq4waMkSKSeR6EvSQj49sKKs4VllcmONfDaXJ+BCcFbhJCkpBv/9+BHQqA7VGoexKKjn4pRhMLpbavOIkgYJhd7lTUsMEETaN5JHv5lLslPQj24eag1CkcSzmNjKkKg4jTlcl9LgEL0CguhhF/tGS75acFm4KpZZW0OEYeIQn+K5q49xPy0S0VBPgam0M9Kkwq5DrXg44ncPBP3bGwe40Hhoa4kx8TD4gT+kfzyv0abTToevAZEBhpXTh+ssQo/ajlwG/cNOqpqFTn6k+ovchhUr5BKUwjjOiaxDG3MnPJU= ansible"
# the privileged user
ansible_user: root
api_user: root@pam
# Marcus Aurelius
# marcus

# the unprivileged user
usr_name: pleb
full_name: Quidam Plebeius

# web applications
domains:
- saelzler.org
# - hearty.cooking
# - vincentsaelzler.com
# - quercusphellos.online




# the certbot role expects a list of ~certificates~
# each certificate could have one or more domains
# CANNOT USE MULTIPLE DOMAINS ON ONE CERT FOR NOW
# TASK [Create symbolic links for intermediate certificate chains]
# fails
certs:
- domains:
  - hearty.cooking
- domains:
  - saelzler.org
# - domains:
#   - vincentsaelzler.com
# - domains:
#   - quercusphellos.online

# credentials
# if the PWs here are not stored externally, and the ansible vault PW is lost,
# THERE IS NO WAY TO RECOVER!!
root_pw: "{{ vault_root_pw }}"
root_pw_salt: "{{ vault_root_pw_salt }}"
usr_pw: "{{ vault_usr_pw }}"
usr_pw_salt: "{{ vault_usr_pw_salt }}"

porkbun_apikey: "{{ vault_porkbun_apikey }}"
porkbun_secretapikey: "{{ vault_porkbun_secretapikey }}"
