---
- name: system level
  hosts: localhost
  become: yes
  roles:
    - ssh-conf
    - git-conf
  tasks:
    - apt:
        pkg: sshpass, python3-proxmoxer

- name: user level
  hosts: localhost
  roles:
    - private-key
  tasks:
    - community.general.ansible_galaxy_install:
        type: role
        name: geerlingguy.docker
    - community.general.ansible_galaxy_install:
        type: role
        name: geerlingguy.certbot
