---
- name: ansible dependencies
  hosts: localhost
  tasks:
    - ansible_galaxy_install:
        type: collection
        name: ansible.posix
    - ansible_galaxy_install:
        type: role
        name: geerlingguy.docker
    - ansible_galaxy_install:
        type: role
        name: geerlingguy.certbot
    - ansible_galaxy_install:
        type: collection
        name: community.docker

- name: system level
  hosts: localhost
  become: yes
  roles:
    - ssh-conf
    - git-conf
  tasks:
    - apt:
        pkg: minicom, code

- name: user level
  hosts: localhost
  roles:
    - private-key
  tasks:
    - command:
        cmd: "code --install-extension {{ item }}"
      with_items:
        - mervin.markdown-formatter
        - redhat.vscode-yaml
