---
- name: system level
  hosts: localhost
  become: yes
  roles:
    - ssh-conf
    - git-conf
  tasks:
    - apt:
        pkg: sshpass, python3-proxmoxer, minicom

- name: user level
  hosts: localhost
  roles:
    - private-key
  tasks:
    - community.general.ansible_galaxy_install:
        type: role
        name: geerlingguy.docker
    - community.general.ansible_galaxy_install:
        type: role
        name: geerlingguy.certbot
    - community.general.ansible_galaxy_install:
        type: collection
        name: community.docker
        force: true
        # state: latest # added in community.general 9.1.0
        # community.docker.docker_compose_v2 # New in community.docker 3.6.0
    - command:
        cmd: "code --install-extension {{ item }}"
      with_items:
        - mervin.markdown-formatter
        - redhat.vscode-yaml
