---
- name: system level
  hosts: localhost
  become: yes
  roles:
  - ssh-conf
  tasks:
  - apt:
      pkg: sshpass, python3-proxmoxer

- name: user level
  hosts: localhost
  roles:
  - aliases
  - private-key
  - vault-pw
  tasks:
  - community.general.ansible_galaxy_install:
      type: role
      name: geerlingguy.certbot, geerlingguy.docker
