---
- name: install nginx package and config file
  hosts: nginx
  tasks:
    - apt:
        pkg: nginx
    - copy:
        src: custom-sites.conf
        dest: /etc/nginx/sites-enabled/

- name: restart nginx to capture changes
  hosts: nginx
  tasks:
    - systemd:
        name: nginx
        state: restarted
        enabled: yes
