---
- name: configure nginx and set pleb user as owner of /var/www
  hosts: revproxy
  become: yes
  tasks:
  # server-level nginx configuration
  - apt:
      pkg: nginx
  - copy:
      src: custom-sites.conf
      dest: /etc/nginx/sites-enabled/

- name: restart nginx to capture changes
  hosts: revproxy
  become: yes
  tasks:
  - systemd:
      name: nginx
      state: restarted
      enabled: yes
