---
- name: add the unprivileged user and update the system
  hosts: revproxy
  # become: yes
  handlers:
  - import_tasks: handlers/main.yml
  roles:
  - pleb-user
  - full-upgrade

- import_playbook: 11-ddns.yml
- import_playbook: 11-certs.yml # dependent on ddns
- import_playbook: 11-websites.yml # dependent on certs
