---
- name: Bootstrap Proxmox Nodes
  hosts: hypervisors
  handlers:
    - import_tasks: handlers/main.yml
  roles:
    - privileged-user
  tasks:

  # # network
  # - name: Check Whether LAN Bridge Configuration Exists
  #   lineinfile:
  #     path: /etc/network/interfaces
  #     line: "iface {{ lan_vbridge }} inet manual"
  #     state: present
  #   check_mode: yes # do not add the line - just check whether it WOULD be added
  #   register: lan_presence

  # - name: Create LAN Bridge
  #   command:
  #     cmd: "pvesh create /nodes/{{ inventory_hostname }}/network --iface {{ lan_vbridge }} --type bridge --autostart true --bridge_ports {{ lan_iface }} --comments LAN"
  #   when: lan_presence.changed # this will NOT run an update - only adds the bridge config if it does not exist.
  #   changed_when: true
  #   notify: Restart

  # repositories
  - name: Disable Enterprise Proxmox Repository
    replace:
      path: /etc/apt/sources.list.d/pve-enterprise.list
      regexp: '^deb'
      replace: '#deb'
    notify:
    - Update and Upgrade
    - Restart

  - name: Disable Enterprise Ceph Repository
    replace:
      path: /etc/apt/sources.list.d/ceph.list
      regexp: '^deb'
      replace: '#deb'
    notify:
    - Update and Upgrade
    - Restart

  - name: Enable No-Subscription Repository
    lineinfile:
      path: /etc/apt/sources.list
      line: "deb http://download.proxmox.com/debian/pve {{ ansible_facts.distribution_release }} pve-no-subscription"
      state: present
    notify:
    - Update and Upgrade
    - Restart

  # pcie passthrough
  - name: Configure Kernel Parameters
    lineinfile:
      path: /etc/kernel/cmdline
      # WARN: on my system, this file didn't exist yet
      # if the file already existed, the text below needs to be added to the
      # end of the existing first line (all variables of this file are on a single line)
      line: amd_iommu=on
      state: present
      create: true
    register: kernel_parms
    notify: Restart

  - name: Apply Kernel Parameters
    command: proxmox-boot-tool refresh
    when: kernel_parms.changed

  - name: Load Kernel Modules
    lineinfile:
      dest: /etc/modules
      line: '{{ item }}'
    with_items:
      - 'vfio'
      - 'vfio_iommu_type1'
      - 'vfio_pci'
      - 'vfio_virqfd'
    register: vfio_modules
    notify: Restart

  - name: Blacklist Drivers
    lineinfile:
      dest: /etc/modprobe.d/blacklist.conf
      line: '{{ item }}'
      create: true
    with_items:
      - 'blacklist amdgpu'
      - 'blacklist radeon'
    register: graphics_modules
    notify: Restart

  - name: Update InitramFS with Modules
    command: update-initramfs -u -k all
    when: vfio_modules.changed or graphics_modules.changed
    notify: Restart
