---
- name: arch linux cloud image
  hosts: pve
  tasks:
    # manually download windows iso

- name: wipe and re-create windows vm
  hosts: pve
  tasks:
    - shell:
        cmd: "qm stop 666 -overrule-shutdown 1 && qm destroy 666 --purge"
      ignore_errors: true # error expected if vm does not exist yet
    - shell: |
        qm create 666 \
        --bios ovmf \
        --boot order="ide0;ide2" \
        --cores 16 \
        --cpu host \
        --efidisk0 local-lvm:0,efitype=4m,pre-enrolled-keys=1 \
        --hostpci0 '0000:09:00,pcie=1,x-vga=1' \
        --hostpci1 '0000:0b:00.3' \
        --ide0 local-lvm:512 \
        --ide2 local:iso/Win11_23H2_English_x64v2.iso,media=cdrom,size=6653034K \
        --machine q35 \
        --memory 16384 \
        --name windows \
        --net0 e1000,bridge=vmbr0,firewall=0 \
        --numa 0 \
        --ostype win11 \
        --scsihw virtio-scsi-single \
        --sockets 1 \
        --tpmstate0 local-lvm:0,version=v2.0

# - name: wait for vm to initialize
#   hosts: workstation
#   gather_facts: no
#   tasks:
#     - name: wait for connectivity
#       wait_for_connection:
#         timeout: 120
