---
- name: core drivers
  hosts: workstation
  handlers:
    - import_tasks: handlers/main.yml
  become: yes
  tasks:
    - pacman:
        update_cache: true
        upgrade: true
      register: syu
      retries: 10
      delay: 6
      until: not syu.failed
      notify: Restart
    - pacman:
        name:
          - qemu-guest-agent
          - linux-firmware
      notify: Restart

- name: user, gui, and packages
  hosts: workstation
  handlers:
    - import_tasks: handlers/main.yml
  become: yes
  tasks:
    - pacman:
        name:
          - gnome
          - git
          - base-devel # aur mkpkg
          - lsof # vscode from aur
          - firefox # oauth in vscode
          - docker
          - radeontop
      notify: Restart
    - user:
        name: axel
        comment: "Axel Rose"
        password: "{{ 'gunsnroses' | password_hash('sha512', pw_salt) }}"
        shell: /bin/bash
        groups: docker
    - authorized_key:
        user: axel
        state: present
        exclusive: yes
        key: "{{ pub_key }}"
    - systemd:
        name: gdm
        enabled: yes
        state: started
    - systemd:
        name: docker
        enabled: yes
        state: started

# - name: create packages from arch user repository
#   hosts: workstation
#   tasks:
#     - file:
#         state: absent
#         path: "/tmp/visual-studio-code-bin/"
#     - git:
#         repo: https://aur.archlinux.org/visual-studio-code-bin.git
#         dest: /tmp/visual-studio-code-bin
#     # Running makepkg as root is not allowed
#     # as it can cause permanent, catastrophic damage to your system.
#     - shell:
#         chdir: /tmp/visual-studio-code-bin
#         cmd: makepkg --clean --force
#     - shell:
#         cmd: ls /tmp/visual-studio-code-bin/ | grep "^visual-studio-code-bin-[0-9]"
#       register: ls
#     - set_fact:
#         package_file: "{{ '/tmp/visual-studio-code-bin/' + ls.stdout }}"

# - name: install aur package
#   hosts: workstation
#   become: yes
#   tasks:
#     - pacman:
#         name: "{{ package_file }}"

# - name: vscode extensions
#   hosts: workstation
#   vars:
#     - ansible_user: axel
#   tasks:
#     - command:
#         cmd: |
#           code --install-extension ms-vscode-remote.remote-containers
