---
- name: user with easy login
  hosts: pve
  tasks:
    - user:
        name: periscope
        password: "{{ 'easypass' | password_hash('sha512', pw_salt) }}"

- name: keys for ssh
  hosts: pve
  vars:
    ansible_user: periscope
  roles:
    - private-key
# - name: application
#   user:
#     name: "{{ usr_name }}"
#     comment: "{{ full_name }}"
#     password: "{{ usr_pw | password_hash('sha512', pw_salt) }}"
