---
- name: Download Container Templates from Proxmox Repository
  hosts: pve
  tasks:
  - name: Check for Latest Debian OS Template
    shell:
      cmd: "pveam available --section system | grep -o debian.* | sort -r | sed 1q"
    register: latest_debian_template
    changed_when: false

  - name: Get Name of Latest Debian Template
    set_fact:
      template_name: "{{ latest_debian_template.stdout }}"

  - name: Download Latest Debian Template
    command:
      cmd: "pveam download local {{ template_name }}"
    register: template_dl
    changed_when: template_dl.stdout_lines | last() != 'calculating checksum of existing file...OK, got correct file already, no need to download'

  - name: print stuff
    debug:
      var: template_name

- name: Create and Start Containers
  hosts: proxmox_cts
  gather_facts: no # fact gathering will fail if the containers don't exist yet
  serial: 1
  vars:
    virt_host_ip: "{{ hostvars['pve']['ansible_host'] }}"
  tasks:

  - name: print stuff
    debug:
      # var: api_user
      # var: root_pw
      # var: virt_host_ip
      # var: disk_size
      # var: tgt_storage
      # var: ram
      # var: vcpus
      # var: ansible_host
      # msg: "name=eth0,ip={{ ansible_host }}/{{ netenv.lan.mask }},bridge={{ netenv.lan.vbridge }}"
      # msg: "name=eth1,ip={{ secondary_ip }}/{{ netenv.wan.mask }},bridge={{ netenv.wan.vbridge }},gw={{ netenv.wan.gw }}"
      var: netconf
      var: dns_srvr
      var: inventory_hostname

  - name: Create New Container
    proxmox:
      # api connectivity
      api_user: "{{ api_user }}"
      api_password: "{{ root_pw }}"
      api_host: "{{ virt_host_ip }}"
      node: pve
      # hardware
      ostemplate: "local:vztmpl/debian-12-standard_12.2-1_amd64.tar.zst"
      # ostemplate: "local:vztmpl/{{ template_name }}"
      disk: "{{ disk_size }}"
      storage: "{{ tgt_storage }}"
      memory: "{{ ram }}"
      swap: 0
      cores: "{{ vcpus }}"
      netif: "{{ netconf }}"
      nameserver: "{{ dns_srvr }}"
      hostname: "{{ inventory_hostname }}"
      # options
      pubkey: "{{ pub_key }}"
      proxmox_default_behavior: no_defaults
      unprivileged: yes
      onboot: yes
      #state: started #apparently cannot create and start containers in one step
    delegate_to: localhost
