---
- name: dependencies and users
  hosts: ddns
  roles:
    - pleb-user
  tasks:
    - apt:
        pkg: git, python3.11-venv

- name: application
  hosts: ddns
  vars:
    ansible_user: "{{ usr_name }}"
  tasks:
    - git:
        repo: https://github.com/VincentSaelzler/porkbun-ddns-pydantic
        dest: "{{ app_dir }}" # does not update/overwrite existing files
    - pip:
        requirements: "{{ app_dir }}/requirements.txt"
        virtualenv: "{{ app_dir }}/.venv"
        virtualenv_command: "python3 -m venv"

- name: systemd service
  hosts: ddns
  tasks:
    - template:
        src: ddns.service
        dest: /etc/systemd/system/

  #   - systemd:
  #       name: ddns
  #       enabled: yes
  #       state: restarted
  #       daemon_reload: yes
