---
- name: do stuff as root
  hosts: dns
  pre_tasks:
    - apt:
        pkg: git, python3.11-venv
  roles:
    - pleb-user
    - git-conf
  tasks:
    - template:
        src: ddns.service
        dest: /etc/systemd/system/
    - copy:
        src: porkbun.env
        dest: /home/pleb/.porkbun.env
        owner: pleb
        group: pleb
    - systemd:
        name: ddns
        enabled: yes
        state: restarted
        daemon_reload: yes

- name: do stuff as pleb
  hosts: dns
  vars:
    ansible_user: "{{ usr_name }}"
  tasks:
#     - git:
#         repo: https://github.com/VincentSaelzler/porkbun-ddns-pydantic
#         dest: ~/porkbun-ddns-pydantic # does not update/overwrite existing files
#     - pip:
#         requirements: ~/porkbun-ddns-pydantic/requirements.txt
#         virtualenv: ~/porkbun-ddns-pydantic/.venv
#         virtualenv_command: "python3 -m venv"

