---
- name: set up the pleb user
  hosts: dns
  roles:
  - pleb-user

- name: configure python script
  hosts: dns
  vars:
    ansible_user: "{{ usr_name }}"
  tasks:
  - name: copy the python script
    template:
      src: domains.py
      dest: ~/domains.py
