---
- name: Install System Stuff (as Root)
  hosts: cookbook
  roles:
  - pleb-user
  tasks:
  - name: Install apt packages
    apt:
      state: present
      pkg:
      - git
      # jekyll
      - ruby-full
      - build-essential
      - zlib1g-dev

  - name:  Create Jekyll Service File
    copy:
      src: jekyll.service
      dest: "/etc/systemd/system/jekyll.service"

- name: Install Jekyll Stuff (as Pleb)
  hosts: cookbook
  vars:
    ansible_user: "{{ usr_name }}"
  tasks:
  - name: clone repo, overwriting any local changes
    git:
      repo: 'https://github.com/VincentSaelzler/cookbook'
      dest: ~/cookbook

  # had zero luck with the ansible gem module, so running command directly
  - name: Install Bundler Gem
    command:
      cmd: "gem install bundler"
    environment: # must be set at the task level (not play) otherwise ansible_facts refer to host
      GEM_HOME: "{{ ansible_facts.env.HOME }}/gems"

  - name: Install Jekyll Site Gems (Using Bundler)
    bundler:
      state: latest
      chdir: ~/cookbook
    environment: # must be set at the task level (not play) otherwise ansible_facts refer to host
      GEM_HOME: "{{ ansible_facts.env.HOME }}/gems"
      PATH: "{{ ansible_facts.env.HOME }}/gems/bin:{{ ansible_facts.env.PATH }}"

- name: Restart and Enable Jekyll System Service (as Root)
  hosts: cookbook
  tasks:
  - name: Restart Jekyll Service
    systemd:
      name: jekyll
      state: restarted
      enabled: yes
