---
- name: Bootstrap Host and Install HAProxy
  hosts: proxy
  tasks:
  - name: Install apt packages
    apt:
      state: present
      pkg:
      - haproxy
  
  - name: Copy the Main Config File
    template:
      src: haproxy.cfg
      dest: "/etc/haproxy/haproxy.cfg"

- name: Generate Let's Encrypt Certificates
  hosts: proxy
  vars:
    # running the app
    certbot_testmode: false
    certbot_install_method: package
    certbot_create_standalone_stop_services:
      - haproxy
    # creating certs
    certbot_create_if_missing: true
    certbot_create_method: standalone
    certbot_admin_email: "{{ usr_email }}"
    certbot_certs: "{{ certs }}"
    # renewing certs
    certbot_auto_renew: true
    certbot_auto_renew_hour: "4"
    certbot_auto_renew_minute: "20"
  roles:
    - geerlingguy.certbot

- name: Use Sym Links so Let's Encrypt certificates Match HAProxy Naming Convention
  hosts: proxy
  tasks:
    - name: Create container directory for certs
      file:
        path: /etc/haproxy/certs/
        state: directory
    - name: Create symbolic links for intermediate certificate chains
      file:
        src: "/etc/letsencrypt/live/{{ item }}/fullchain.pem"
        dest: "/etc/haproxy/certs/{{ item }}"
        state: link
      loop: "{{ domains }}"

    - name: Create symbolic links for private key files
      file:
        src: "/etc/letsencrypt/live/{{ item }}/privkey.pem"
        dest: "/etc/haproxy/certs/{{ item }}.key"
        state: link
      loop: "{{ domains }}"
  
    - name: Restart haproxy service
      systemd:
        name: haproxy
        state: restarted
        enabled: yes
      register: systemctl
      retries: 10
      delay: 3
      until: not systemctl.failed # The certbot role (sometimes) prevents haproxy from restarting for a few seconds.
