---
- name: Install System Packages
  hosts: cookbook
  tasks:
  - name: Install apt packages
    apt:
      state: present
      pkg:
      - git
      # jekyll
      - ruby-full
      - build-essential
      - zlib1g-dev
      # dependencies to shrink photos using the photo-shrink.py script
      - imagemagick
      - python3
  - debug:
      var: ansible_user

  # - name: Install Bundler Gem
  #   command:
  #     cmd: "gem install --user-install bundler"

- name: Install Packages
  hosts: cookbook
  vars:
    ansible_user: pleb
  # environment:
  #   GEM_HOME: "{{ ansible_facts.env.HOME }}/gems"

  tasks:
  - name: Clone if Not Exists, Otherwise Leave Container's Repo Untouched
    git:
      repo: 'https://github.com/VincentSaelzler/cookbook'
      dest: ~/cookbook
      update: no

  - name: Install Bundler Gem
    command:
      cmd: "gem install bundler"
    environment:
      GEM_HOME: "{{ ansible_facts.env.HOME }}/gems"

  # ansible ignores ~/.bashrc stuff - this is for using the container interactively  
  - name: Specify Where to Save Gems
    lineinfile:
      dest: ~/.bashrc
      line: 'export GEM_HOME="$HOME/gems"'

  - name: Make Gems Executable
    lineinfile:
      dest: ~/.bashrc
      line: 'export PATH="$HOME/gems/bin:$PATH"'

  - name: Install Jekyll Site Gems (Using Bundler)
    bundler:
      state: latest
      chdir: ~/cookbook
    environment:
      GEM_HOME: "{{ ansible_facts.env.HOME }}/gems"
      PATH: "{{ ansible_facts.env.HOME }}/gems/bin:{{ ansible_facts.env.PATH }}"

  # - debug:
  #     var: ansible_facts.env.PATH
  # - command:
  #     cmd: echo $PATH
  #   environment:
  #     GEM_HOME: "{{ ansible_facts.env.HOME }}/gems"
  #     PATH: "{{ ansible_facts.env.HOME }}/gems/bin:{{ ansible_facts.env.PATH }}"

#https://stackoverflow.com/questions/22115936/install-bundler-gem-using-ansible
#It's all about the paths.