---
- name: blob storage to ansible host
  hosts: jekyllsites
  vars:
    # this is the critical integration handoff point
    # the inventory_hostname must match the name of the file on azure
    remote_blob: "{{ inventory_hostname }}-site.tar.gz"
    local_archive: "/tmp/{{ remote_blob }}"
  tasks:
  # delegate to local ansible host to keep azure
  # permissions and dependencies off public webserver
  # manually run `az login` before running this play
  - name: download website contents
    delegate_to: localhost
    azure_rm_storageblob:
      resource_group: Websites
      storage_account_name: saelzlerwebsites
      container: deployment
      blob: "{{ remote_blob }}"
      dest: "{{ local_archive }}"
      force: true # reports "changed" regardless of whether file is any different

  - name: install nginx
    apt:
      state: present
      pkg: nginx

  - name: wipe nginx site folder
    file:
      state: absent
      path: /var/www/html/

  - name: recreate (empty) nginx site folder
    file:
      state: directory
      path: /var/www/html/

  - name: ansible host archive to nginx site folder
    unarchive:
      src: "{{ local_archive }}"
      dest: /var/www/html

  - name: restart nginx
    systemd:
      name: nginx
      state: restarted
      enabled: yes
