---
- name: clone website repositories and build sites
  hosts: localhost
  tasks:
  - file:
      path: /tmp/websites
      state: absent
  - git:
      repo: "https://github.com/VincentSaelzler/websites"
      dest: /tmp/websites
      recursive: yes
  # manually run `sudo bundle install`
  # using vscode in website repo
  # long term need to figure out how to user-level install
  - command: bundle exec jekyll build
    args:
      chdir: /tmp/websites/love

- name: configure nginx and copy site contents to /var/www
  hosts: model4b
  become: yes
  tasks:
  # server-level nginx configuration
  - apt:
      state: present
      pkg: nginx
  - copy:
      src: custom-sites.conf
      dest: /etc/nginx/sites-enabled/
  # individual site contents
  - synchronize:
      src: /tmp/websites/love/_site/
      dest: /var/www/bethanyandvincent.com/
      delete: yes
      recursive: yes
  # restart to capture changes
  - systemd:
      name: nginx
      state: restarted
      enabled: yes
