---
- name: Install System Stuff (as Root)
  hosts: wedding
  roles:
  - pleb-user
  tasks:
  - name: Install apt packages
    apt:
      state: present
      pkg:
      - git
      - nginx
      # jekyll
      - ruby-full
      - build-essential
      - zlib1g-dev

  - name: change ownership of the default site folder
    file:
      path: /var/www/html/
      state: directory
      recurse: yes
      owner: "{{ usr_name }}"
      group: "{{ usr_name }}"

- name: Install Jekyll Stuff (as Pleb)
  hosts: wedding
  vars:
    ansible_user: "{{ usr_name }}"
  tasks:
  - name: clone repo, overwriting any local changes
    git:
      repo: 'https://github.com/VincentSaelzler/wedding'
      dest: ~/wedding
      force: true

  # had zero luck with the ansible gem module, so running command directly
  - name: Install Bundler Gem
    command:
      cmd: "gem install bundler"
    environment: # must be set at the task level (not play) otherwise ansible_facts refer to host
      GEM_HOME: "{{ ansible_facts.env.HOME }}/gems"

  - name: Install Jekyll Site Gems (Using Bundler)
    bundler:
      state: latest
      chdir: ~/wedding/website
    environment: # must be set at the task level (not play) otherwise ansible_facts refer to host
      GEM_HOME: "{{ ansible_facts.env.HOME }}/gems"
      PATH: "{{ ansible_facts.env.HOME }}/gems/bin:{{ ansible_facts.env.PATH }}"
  
  - name: build the production site
    command:
      cmd: "bundle exec jekyll build --destination /var/www/html/"
      chdir: ~/wedding/website
    environment: # must be set at the task level (not play) otherwise ansible_facts refer to host
      GEM_HOME: "{{ ansible_facts.env.HOME }}/gems"
      PATH: "{{ ansible_facts.env.HOME }}/gems/bin:{{ ansible_facts.env.PATH }}"
      JEKYLL_ENV: production

- name: restart nginx (as root)
  hosts: wedding
  tasks:
  - name: restart nginx
    systemd:
      name: nginx
      state: restarted
      enabled: yes
