---
- name: install docker
  hosts: moby
  roles:
  - pleb-user
  - geerlingguy.docker
  vars:
    docker_users: "{{ usr_name }}"

- name: frigate
  hosts: moby
  vars:
    ansible_user: "{{ usr_name }}"
  tasks:
  - copy:
      src: docker-compose.yml
      dest: ~/frigate/
  # - copy:
  #     src: frigate-config.yaml
  #     dest: ~/frigate/config/config.yaml
  - community.docker.docker_compose_v2:
      project_src: ~/frigate/
      # manually run docker logs frigate and look for password



