---
- name: install docker
  hosts: frigate
  roles:
  - pleb-user
  - geerlingguy.docker
  vars:
    docker_users: "{{ usr_name }}"

- name: frigate
  hosts: frigate
  vars:
    ansible_user: "{{ usr_name }}"
  tasks:
  - copy:
      src: docker-compose.yml
      dest: ~/frigate/
  - copy:
      src: frigate-config.ymel
      dest: ~/frigate/config.yaml
  - community.docker.docker_compose_v2:
      project_src: ~/frigate/
    # manually run docker logs frigate and look for password
