# AFTER COMPLETION OF PLAYBOOK
# MANUALLY FIND AND CHANGE PASSWORD
# ssh pleb@frigate
# docker logs frigate | grep 'Password: '
# https://saelzler.org
# https://frigate.local:8971
---
- name: install docker
  hosts: frigate
  roles:
    - geerlingguy.docker
  vars:
  tasks:
    - apt:
        pkg: htop

# run docker container as root to prevent permissions issues
# passing gpu hardware devices through
- name: install frigate
  hosts: frigate
  tasks:
    - copy:
        src: frigate-compose.yml
        dest: ~/docker-compose.yml
    - file:
        path: ~/config
        state: directory
    - copy:
        src: yolo_nas_s.onnx
        dest: ~/config/
    - template:
        src: frigate-config.yml
        dest: ~/config/config.yaml
    - file:
        path: ~/media
        state: directory
    # - community.docker.docker_compose_v2:
    #     project_src: ~/
