# AFTER COMPLETION OF PLAYBOOK
# MANUALLY FIND AND CHANGE PASSWORD
# ssh pleb@frigate
# docker logs frigate | grep 'Password: '
# https://saelzler.org
# https://frigate.local:8971
---
- name: install docker
  hosts: frigate
  roles:
    - pleb-user
    - geerlingguy.docker
  vars:
    docker_users: "{{ usr_name }}"
  tasks:
    - apt:
        pkg: htop

- name: install frigate
  hosts: frigate
  vars:
    ansible_user: "{{ usr_name }}"
  tasks:
    - copy:
        src: docker-compose.yml
        dest: ~/
    - file:
        path: ~/config
        state: directory
    - copy:
        src: frigate-config.yml
        dest: ~/config/config.yaml
    - file:
        path: ~/media
        state: directory
    - community.docker.docker_compose_v2:
        project_src: ~/
