---
- name: --------------------------- host configuration
  hosts: localhost
  become: yes
  roles:
    - ssh-conf
    - git-conf
  tasks:
  - name: apt packages
    apt:
      pkg:
        - python3-pip # azcollection and proxmoxer
        - sshpass # bootstrap bare-metal proxmox nodes
        - curl # download azure cli install script
        - ruby-full # jekyll
        - build-essential # jekyll
        - zlib1g-dev # jekyll
        - imagemagick # photoshrink.py
  - name: bundler # jekyll dependency management
    shell:
      cmd: "gem install bundler"       
  - name: azure cli
    shell:
      cmd: "curl -sL https://aka.ms/InstallAzureCLIDeb | bash"  
  - name: certbot
    community.general.ansible_galaxy_install:
      type: role
      name: geerlingguy.certbot
  - name: azcollection from galaxy
    community.general.ansible_galaxy_install:
      type: collection
      name: azure.azcollection
  - name: azcollection python dependencies
    pip:
      # locate requirements file in folder where collection is installed
      # ansible-galaxy collection list -vvv | grep azure.azcollection
      requirements: /usr/local/lib/python3.10/dist-packages/ansible_collections/azure/azcollection/requirements-azure.txt
  - name: proxmoxer python dependencies
    pip:
      name:
      - proxmoxer
      # - requests #tbc if required

- name: --------------------------- user configuration
  hosts: localhost
  vars_prompt:
  - name: wipe_keyair
    prompt: Should we OVERWRITE the existing public/private keypair? This WIPES existing contents of ~/.ssh/id_rsa and ~/.ssh/id_rsa.pub
    private: no
    default: "y"
  roles:
      - aliases
      - vault-pw
  tasks:
  - name: Install Public/Private Keypair
    import_role:
      name: private-key
    when: wipe_keyair == "y" or wipe_keyair == "Y"



