---
- name: dependencies and users
  hosts: moby
  roles:
    - pleb-user
  tasks:
    - apt:
        pkg: docker
    # - pacman:
    #     name:
    #       - gnome
    #       - git
    #       - base-devel # aur mkpkg
    #       - lsof # vscode from aur
    #       - firefox # oauth in vscode
    #       - docker
    #       - radeontop
    #   notify: Restart

          # shell: /bin/false
    #     shell: /bin/bash
    #     groups: docker
    # - authorized_key:
    #     user: axel
    #     state: present
    #     exclusive: yes
    #     key: "{{ pub_key }}"

    # checksum: "{{ dest_checksum }}"
